server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      # 数据库索引(默认为0)
      database: 2
      # 连接超时时间
      timeout: 3000ms
      # 密码(没有密码可以省略)
      password: 123456
      # 连接池配置
      lettuce:
        pool:
           # 连接池最大连接数(使用负值表示没有限制)
           max-active: 20
           # 连接池最大阻塞等待时间(使用负值表示没有限制)
           max-wait: -1ms
           # 连接池中的最大空闲连接
           max-idle: 10
           # 连接池中的最小空闲连接
           min-idle: 2
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss #日期格式
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # ✅ 开启驼峰命名
  mapper-locations: classpath*:mapper/**/*.xml


  #type-aliases-package: com.pxy.user.entity
#  security:
#    user:
#      password: 123456
